apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-restricted-runtime-default-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-restricted-runtime-default-scc
subjects:
  - kind: ServiceAccount
    namespace: openshift-operators
    name: cert-manager
  - kind: ServiceAccount
    namespace: openshift-operators
    name: cert-manager-cainjector
  - kind: ServiceAccount
    namespace: openshift-operators
    name: cert-manager-webhook
