apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: cert-manager
resources:
- ../../base/operators.coreos.com/subscriptions/cert-manager
- ../../base/cert-manager.io/clusterissuers/selfsigned
