apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret3
  namespace: default
spec:
  secretStoreRef:
    name: tajcluster-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: demo-secret
  data:
  - secretKey: password
    remoteRef:
      key: tajcluster/data/test/demosecret
      property: password
