apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    name: tajcluster-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: github-client-secret
    template:
      metadata:
        labels: {}
  data:
    - secretKey: clientSecret
      remoteRef:
        key: REPLACE_IN_OVERLAY
        property: clientSecret
