apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tajcluster-cluster-secrets
spec:
  provider:
    vault:
      server: "http://vault-ui-vault.apps.tajcluster.int.massopen.cloud/"
      path: "tajcluster"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes/
          role: devweb-app
          serviceAccountRef:
            name: "vault-secret-reader"
            namespace: "external-secrets-operator"
