apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/namespaces/kubevirt-hostpath-provisioner
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/kubevirt-hostpath-provisioner
- ../../base/storage.k8s.io/storageclasses/kubevirt-hostpath-provisioner
- ../../base/security.openshift.io/securitycontextconstraints/hostpath-provisioner
- ../../base/rbac.authorization.k8s.io/clusterroles/kubevirt-hostpath-provisioner
- ../../base/machineconfiguration.openshift.io/machineconfigs/hostpath-provisioner-selinux
