apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/core/serviceaccounts/vault-secret-reader
- ../../base/external-secrets.io/clustersecretstores/test-cluster-secrets
