apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-route53-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: nerc-secret-store
  target:
    name: aws-route53-credentials
    template:
      metadata:
        labels: {}
  dataFrom:
    - extract:
        key: REPLACE_IN_OVERLAY
