apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-group-sync
  namespace: group-sync-operator
spec:
  secretStoreRef:
    name: tajcluster-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: github-group-sync
  data:
  - secretKey: appId
    remoteRef:
      key: tajcluster/data/test-cluster/openshift-config/group-sync
      property: appId
  - secretKey: privateKey
    remoteRef:
      key: tajcluster/data/test-cluster/openshift-config/group-sync
      property: privateKey
