apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/external-secrets-clustersecretstore
- ../../bundles/kubevirt-hostpath-provisioner
- ../../../hostpath-provisioner/base
- ../../../vault/base
- externalsecrets
- apiserver/cluster.yaml
- certificates

components:
  - ../../components/test-certificate-issuer
  - ../../components/tajcluster-oauth-github

generatorOptions:
  disableNameSuffixHash: true

patches:
