apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common
- ../../bundles/external-secrets-clustersecretstore
- ../../bundles/hostpath-provisioner
- ../../bundles/vault
- ../../../hostpath-provisioner/base
- ../../../vault/base
- externalsecrets
- apiserver/cluster.yaml
- certificates

components:
  - ../../components/test-certificate-issuer
  - ../../components/tajcluster-oauth-github

generatorOptions:
  disableNameSuffixHash: true

patches:
- patch: |
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: github
        github:
          clientID: 6b5aae649836181457ea
- target:
    kind: ExternalSecret
    name: aws-route53-credentials
  patch: |
    - op: replace
      path: /spec/dataFrom/0/extract/key
      value: tajclustersecrets/aws
- target:
    kind: ExternalSecret
    name: github-client-secret
  patch: |
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: tajclustersecrets/github
- target:
    kind: APIServer
    name: cluster
  patch: |
    - op: replace
      path: /spec/servingCerts/namedCertificates/0/names/0
      value: api.tajcluster.int.massopen.cloud
